yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.IndexListView.as_view(),
        name='index'
    ),
    path(
        'create/',
        views.PostCreateView.as_view(),
        name='post_create'
    ),
    path(
        'profile/<str:username>/',
        views.ProfileListView.as_view(),
        name='profile'
    ),
    path(
        'group/<slug:slug>/',
        views.GroupListView.as_view(),
        name='group_list'
    ),
    path(
        'posts/<int:post_id>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.PostEditView.as_view(),
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.AddCommentView.as_view(),
        name='add_comment'
    ),
    path(
        'follow/',
        views.FollowListView.as_view(),
        name='follow_index',
    ),
    path(
        'profile/<str:username>/follow/',
        views.ProfileFollowView.as_view(),
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.ProfileUnFollowView.as_view(),
        name='profile_unfollow',
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LogoutView, LoginView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SingUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'

    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Group(models.Model):
    """Модель для сообществ."""
    title = models.CharField(
        'Название',
        max_length=200,
        help_text='Название не должно превышать 200 символов.',
    )
    slug = models.SlugField(
        'slug',
        unique=True,
        help_text='Должен быть уникальным.',
    )
    description = models.TextField(
        'Описание',
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    """Модель для постов."""
    text = models.TextField(
        'Текст',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Сообщество',
        help_text='Данный параметр необязательный'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.pk})


class Comment(models.Model):
    """Модель для комментариев."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        'Текст',
        help_text='Текст комментария',
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.post_id})


class Follow(models.Model):
    """Модель для подписок на авторов."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_following'),
        ]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    """Форма для создания/редактирования нового поста."""

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(ModelForm):
    """Форма для создания/редактирования комментария."""

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic.base import RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow
from .utils import AuthorRequiredMixin


@method_decorator(cache_page(20, key_prefix='index_page'), name='dispatch')
class IndexListView(ListView):
    """Главная страница, на которой отображаются все посты пользователей."""
    model = Post
    paginate_by = settings.POSTS_PER_PAGE
    template_name = 'posts/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['index'] = True
        return context


class GroupListView(ListView):
    """Страница с постами определенной группы."""
    paginate_by = settings.POSTS_PER_PAGE
    template_name = 'posts/group_list.html'

    def get_queryset(self):
        self.group = get_object_or_404(Group, slug=self.kwargs['slug'])
        return self.group.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = self.group
        return context


class ProfileListView(ListView):
    """Страница-profile определенного юзера."""
    paginate_by = settings.POSTS_PER_PAGE
    template_name = 'posts/profile.html'

    def get_queryset(self):
        self.author = get_object_or_404(User, username=self.kwargs['username'])
        return self.author.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        context['following'] = self.is_follow()
        return context

    def is_follow(self) -> bool:
        if not self.request.user.is_authenticated:
            return False
        return Follow.objects.filter(
            user=self.request.user,
            author=self.author,
        ).exists()


class PostDetailView(DetailView):
    """Подробная страница определенного поста."""
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all()
        context['form'] = CommentForm()
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    """Страница создания нового поста."""
    template_name = 'posts/create_post.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse(
            'posts:profile',
            kwargs={'username': self.object.author.get_username()},
        )

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = False
        return context


class PostEditView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Страница редактирования определенного поста."""
    model = Post
    template_name = 'posts/create_post.html'
    form_class = PostForm
    pk_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class AddCommentView(LoginRequiredMixin, CreateView):
    """Создание нового комментария к посту."""
    http_method_names = ['post']
    form_class = CommentForm

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        form.instance.author = self.request.user
        form.instance.post = post
        return super().form_valid(form)


class FollowListView(LoginRequiredMixin, ListView):
    """Страница с постами авторов, на который подписан пользователь."""
    model = Post
    paginate_by = settings.POSTS_PER_PAGE
    template_name = 'posts/follow.html'

    def get_queryset(self):
        return Post.objects.filter(author__following__user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['follow'] = True
        return context


class ProfileFollowView(LoginRequiredMixin, RedirectView):
    """Создание подписки на определенного автора."""
    pattern_name = 'posts:profile'

    def get(self, request, *args, **kwargs):
        self.follow()
        return super().get(request, *args, **kwargs)

    def follow(self):
        author = get_object_or_404(User, username=self.kwargs['username'])
        if author != self.request.user:
            Follow.objects.get_or_create(
                user=self.request.user,
                author=author,
            )


class ProfileUnFollowView(LoginRequiredMixin, RedirectView):
    """Отмена подписки на определенного автора."""
    pattern_name = 'posts:profile'

    def get(self, request, *args, **kwargs):
        self.unfollow()
        return super().get(request, *args, **kwargs)

    def unfollow(self):
        author = get_object_or_404(User, username=self.kwargs['username'])
        Follow.objects.filter(
            user=self.request.user,
            author=author
            ).delete()

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</div>

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/form_field.html
{% load user_filters %}

{% csrf_token %}

{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %}
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}"
          >
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
               href="{% url 'posts:post_create' %}"
            >
              Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %} link-light"
               href="{% url 'users:password_change' %}"
            >
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'user:logout' %}active{% endif %} link-light"
               href="{% url 'users:logout' %}"
            >
              Выйти
            </a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %} link-light"
               href="{% url 'users:login' %}"
            >
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %} link-light"
               href="{% url 'users:signup' %}"
            >
              Регистрация
            </a>
          </li>
        {% endif %}
      {% endwith %}
</ul>
  </div>
</nav>

yatube/templates/includes/post.html
{% load thumbnail %}

<ul>
  <li>
    Автор:
    <a href="{% url 'posts:profile' post.author.get_username %}">{{ post.author.get_full_name }}</a>
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text|linebreaksbr }}</p>
{% if post.group %}
  <p>
    Группа:
    <a href="{% url 'posts:group_list' post.group.slug %}">
      {{ post.group.title }}
    </a>
  </p>
{% endif %}
<a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>